services:
  abiotic-server:
    image: "IrvinEdgarSmith/abiotic-factor-linux-docker:latest"
    restart: unless-stopped
    volumes:
      - "./gamefiles:/server"
      - "./data:/server/AbioticFactor/Saved"
    environment:
      - MaxServerPlayers=6
      - Port=7777
      - QueryPort=27015
      - ServerPassword=Timgdapw2791!
      - SteamServerName=MycelialLaboratory
      - UsePerfThreads=true
      - NoAsyncLoadingThread=true
      - WorldSaveName=MycelialSave
#     - AutoUpdate=true
#     - AdditionalArgs=-SandboxIniPath=Config/WindowsServer/Server1Sandbox.ini
      - DISCORD_WEBOOK_URL: <discord webhook url here>
    ports:
      - "0.0.0.0:7777:7777/udp"
      - "0.0.0.0:27015:27015/udp"
